server:
  port: 9000

spring:
  application:
    name: filestorage
  cloud:
    config:
      enabled: false
  # Actuator
  management:
    endpoints:
      web:
        exposure:
          include: env
  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/db_ecommerce_storage
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
#    url: jdbc:postgresql://localhost:5432/db_storage
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5

  # MultipartFile
  servlet:
    multipart:
      max-file-size: 6GB
      max-request-size: 6GB